name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependencies:
    name: "Dependencies (PHP ${{ matrix.php-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.3, 8.4]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer
      - name: Composer cache config
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - run: composer validate --strict
      - run: composer install --prefer-dist --no-progress
      - run: composer audit

  cs:
    name: "Code Style (php-cs-fixer)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: php-cs-fixer
      - run: php-cs-fixer -V
      - run: php-cs-fixer fix --dry-run --diff

  static_analysis:
    name: "Static Analysis (PHPStan)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: phpstan
      - name: Composer cache config
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - run: composer validate --strict
      - run: composer install --prefer-dist --no-progress
      - run: phpstan --version
      - run: phpstan analyse src/

  tests:
    name: "Tests (PHP ${{ matrix.php-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.3, 8.4]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - name: Composer cache config
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - run: composer validate --strict
      - run: composer install --prefer-dist --no-progress
      - run: ./vendor/bin/phpunit --version
      - name: PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Upload coverage to Codecov
        if: matrix.php-version == '8.4'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
